version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - 27018:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: "bioskin"
        MONGO_INITDB_ROOT_PASSWORD: "12345"
        MONGO_INITDB_DATABASE: bd_projects
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./backend/rest/bd:/db-dump
    networks:
      - network_project
  backend:
    container_name: backend_container
    restart: always
    ports:
      - 3000:3000
    build: ./backend
    depends_on:
      - mongodb
    command: "npm run dev"
    networks:
      - network_project
  frontend:
    container_name: frontend_container
    restart: always
    ports:
      - 4200:4200
    build: ./frontend
    depends_on:
      - backend
    networks:
      - network_project
  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   container_name: adminMongo_container
  #   depends_on:
  #     - "mongodb"
  # loadbalancer:
  #   image: nginx:latest
    
  #   command: nginx -g daemon off

networks:
  network_project: